Multiplication after division
Stacktical/stacktical-dsla-contracts pull request #148
Opened 2022-06-01 00:14 UTC by gmtesla

This PR updates math operations to do multiplication first before division during the calculations to avoid rounding issues of Solidity math.

2022-06-01 08:12 UTC, wilhempujar requested changes
OK but instead of using a hardcode 4, best to use a constant.

2022-06-01 10:16 UTC, gmtesla commented
> OK but instead of using a hardcode 4, best to use a constant.
I don't think that's good.
If we define a constant value, when calculating the getDeviation, it will access to the storage to get this constant and it will take more gas fees.

2022-06-01 13:46 UTC, bussyjd approved these changes
LGTM

2022-06-01 14:16 UTC, wilhempujar commented on contracts/SLORegistry.sol
> +    uint16 private constant deviationCapPercent = 2500;
`deviationCap` better?

We're not using the "percent" suffix for any of the percentage in the protocol.

2022-06-01 14:17 UTC, wilhempujar commented on contracts/Staking.sol
> +            if (reward > usersPool[tokenAddress] / 4) {
Should use `deviationCap`

2022-06-01 14:17 UTC, wilhempujar commented on contracts/Staking.sol
> +            if (compensation > providersPool[tokenAddress] / 4) {
Should use `deviationCap`

2022-06-02 08:23 UTC, wilhempujar commented on contracts/Staking.sol
> +    uint16 private constant rewardsCapRate = 2500;
Don't see this being used anywhere (yet)?

2022-06-03 12:17 UTC, wilhempujar approved these changes
LGTM

2022-06-03 12:17 UTC, merged