Drawdown control w/ user-defined Severity & Penalty Levels
Stacktical/stacktical-dsla-contracts pull request #162
Opened 2022-10-10 14:06 UTC by wilhempujar

This patch provides an alternate, user-defined reward calculation approach vs the default deviation formula that we use in the SLO registry. 

It allows the contract creator to define severity levels, and their respective penalties.
If the SLI is equal or greater than the value of a severity level `severity[i]`, than `penalty[i]` becomes the deviation.

In DSLA v2.0, deviation = reward.

In parametric staking, this gives the contract creator a way to control the drawdown of the liquidity pool based on the price increase of the underlying asset. For the DSLA token:
* **Severity 1**: Any increase under 100% = 1% deviation
* **Severity 2**: An increase of 100%+ = 10% deviation
* **Severity 3**: An increase of 250%+ = 25% deviation

25% is also the protocol-level cap on rewards.

2022-10-10 14:33 UTC, Axel-CH commented on contracts/SLORegistry.sol
> +        for (uint256 i = 0; i < severity.length; i++) {
What append if the arrays don't have the same length? Should we add a check to validate that they have?

2022-10-10 14:37 UTC, Axel-CH commented on contracts/SLORegistry.sol
> +        if (deviation == 0) {
If I have created two arrays of penalty / severity but for some reason at one time the deviation is equal to 0.
I will fall back to the previous formula and my custom penalty won't be respected.

I think we need to replace this with a check of presence / length of penalty / severity arrays

2022-10-10 14:39 UTC, Axel-CH requested changes
Great changes that will enable more customization on SLA outcome, need to update tests with new createSLA params

2022-10-11 11:36 UTC, wilhempujar commented on contracts/SLORegistry.sol
> +        if (deviation == 0) {
If the deviation equals 0, meaning `penalty[i] = 0`, we can assume that's what the user wants imho. It makes a nice fallback to the default behaviour, when using custom severities.

2022-10-11 12:54 UTC, wilhempujar commented
> Great changes that will enable more customization on SLA outcome, need to update tests with new createSLA params

Tests updated / Passing ☑️

LFG?

2022-10-11 13:06 UTC, Axel-CH commented
Specific tests for user defined severity & penalty levels should be added imo, beside that great work. LGTM :+1:

2022-10-11 20:04 UTC, Axel-CH approved these changes

2022-10-11 20:04 UTC, Axel-CH commented on contracts/SLORegistry.sol
> +        if (deviation == 0) {
Are we sure that the deviation will stay at zero after the fallback to default formula, as this formula is based on the SLO / SLI delta?

2022-10-14 22:00 UTC, merged